package com.grenefolc.hildr;

public final class HildrDefaults {

    private HildrDefaults() {
    }

    public static String defaultBehaviorConfigJson() {
        return "{"
                + "\"cli\":{"
                + "\"showCliSettings\":false,"
                + "\"showDelimiterSettings\":false,"
                + "\"showEnvelopeFilter\":false,"
                + "\"showRecognitionRe\":false,"
                + "\"showSourceRecord\":false,"
                + "\"showProcessTrace\":false,"
                + "\"envelopeFilter\":true,"
                + "\"synonymStyle\":\"id\","
                + "\"presentationClass\":\"\","
                + "\"maxOccurs\":\"none\""
                + "},"
                + "\"logging\":{"
                + "\"showRawCliJson\":false,"
                + "\"showRawRecogJson\":false,"
                + "\"showFullTrace\":false"
                + "}"
                + "}";
    }

    public static String defaultRecognitionSpecJson() {
        return "{"
                + "\"-init\":{"
                + "\"-domain\":\"vartala\","
                + "\"-headLimit\":\"160\""
                + "},"
                + "\"-recognition\":["
                + "{"
                + "\"-mask\":\"EDI_DC40\","
                + "\"-profile\":\"sapidoc\""
                + "},"
                + "{"
                + "\"-mask\":\"(UNA|UNB|UNH)\","
                + "\"-profile\":\"edifact\""
                + "},"
                + "{"
                + "\"-mask\":\"(STX|MHD)\","
                + "\"-profile\":\"tradacoms\""
                + "},"
                + "{"
                + "\"-mask\":\"ISA...............................................................................[[:punct:]]\","
                + "\"-profile\":\"x12-gt4010\""
                + "},"
                + "{"
                + "\"-mask\":\"ISA...............................................................................[[:alnum:]]\","
                + "\"-profile\":\"x12-le4010\""
                + "}"
                + "],"
                + "\"-profile\":{"
                + "\"edifact\":{"
                + "\"-format\":\"csv\","
                + "\"-envelope\":{\"-head\":\"UNB\",\"-tail\":\"UNZ\"},"
                + "\"-separators\":{"
                + "\"-dynamic\":\"-/UNA/UNA&element;&composite;&decimal;&release;&repetition;&segment;\","
                + "\"-default\":{"
                + "\"&element;\":\":\","
                + "\"&composite;\":\"+\","
                + "\"&decimal;\":\".\","
                + "\"&release;\":\"?\","
                + "\"&repetition;\":\"\","
                + "\"&segment;\":\"'\""
                + "}"
                + "}"
                + "},"
                + "\"tradacoms\":{"
                + "\"-format\":\"csv\","
                + "\"-envelope\":{\"-head\":\"STX\",\"-tail\":\"END\"},"
                + "\"-separators\":{"
                + "\"-default\":{"
                + "\"&tag;\":\"=\","
                + "\"&element;\":\":\","
                + "\"&composite;\":\"+\","
                + "\"&decimal;\":\".\","
                + "\"&release;\":\"?\","
                + "\"&repetition;\":\"\","
                + "\"&segment;\":\"'\""
                + "}"
                + "}"
                + "},"
                + "\"x12-gt4010\":{"
                + "\"-format\":\"csv\","
                + "\"-envelope\":{\"-head\":\"ISA|GS\",\"-tail\":\"GE|IEA\"},"
                + "\"-separators\":{"
                + "\"-dynamic\":\"+/ISA/ISA&composite;v....1....v....2....v....3....v....4....v....5....v....6....v....7....v....8..&repetition;.v....9....v....X....&element;&segment;\","
                + "\"-default\":{"
                + "\"&tag;\":\"*\","
                + "\"&element;\":\":\","
                + "\"&composite;\":\"*\","
                + "\"&decimal;\":\".\","
                + "\"&release;\":\"!\","
                + "\"&repetition;\":\"+\","
                + "\"&segment;\":\"~\""
                + "}"
                + "}"
                + "},"
                + "\"x12-le4010\":{"
                + "\"-format\":\"csv\","
                + "\"-envelope\":{\"-head\":\"ISA|GS\",\"-tail\":\"GE|IEA\"},"
                + "\"-separators\":{"
                + "\"-dynamic\":\"+/ISA/ISA&composite;v....1....v....2....v....3....v....4....v....5....v....6....v....7....v....8....v....9....v....X....&element;&segment;\","
                + "\"-default\":{"
                + "\"&element;\":\":\","
                + "\"&composite;\":\"*\","
                + "\"&decimal;\":\".\","
                + "\"&release;\":\"!\","
                + "\"&repetition;\":\"+\","
                + "\"&segment;\":\"~\""
                + "}"
                + "}"
                + "},"
                + "\"sapidoc\":{"
                + "\"-format\":\"ffv\""
                + "}"
                + "}"
                + "}";
    }
}
